//! Executor entry points.
//!
//! [`execute`] dispatches one parsed statement. M1 semantics: every
//! statement autocommits -- reads run at the oracle's `now()` snapshot,
//! writes allocate a fresh timestamp per batch. M2 layers explicit
//! BEGIN/COMMIT snapshot transactions on top of the same entry point.

pub mod agg;
/// Correlated-subquery binding (per outer-row pre-computation) plus
/// the column-rewrite traversal it shares with detection.
mod correlated;
mod correlated_map;
pub mod ddl;
/// ALTER-family DDL (M4): CREATE/DROP INDEX backfills, TRUNCATE and
/// RENAME TABLE, all riding `ddl`'s raft-guarded catalog machinery.
pub(crate) mod ddl_alter;
pub mod expr;
mod expr_decimal;
/// Scalar-function family dispatch (pure, stateless): the single
/// `eval_func` entry plus the CASE/CAST/bit-op helpers the expression
/// executor routes through.
pub mod func;
/// Row construction shared by every INSERT source (VALUES / SELECT /
/// SET-normalized): column-list mapping, coercion, NOT NULL.
pub(crate) mod insert_common;
/// INSERT ... SELECT source materialization: the source query runs to
/// completion before any write of the statement.
pub(crate) mod insert_select;
pub mod relation;
pub mod render;
pub mod scan;
pub mod select;
pub mod sequence;
/// Session scalar functions (DATABASE()/USER()/CONNECTION_ID()):
/// per-execution binding of the immutable session snapshot into the
/// statement's expression trees (pure substitution, no globals).
mod session_funcs;
pub mod set_ops;
pub mod show;
pub mod subquery;
/// Explicit INSERT conflict paths: ON DUPLICATE KEY UPDATE / REPLACE.
pub(crate) mod upsert;
pub mod write;
mod write_probe;

use crate::sql::parse::ast::Statement;
use crate::sql::parse::error::{ErrorCode, SqlError, SqlResult};
use crate::sql::storage::schema::SqlType;
use crate::sql::tx;
use crate::state::Shared;

/// Result column metadata (name + wire type) for row-producing statements.
#[derive(Debug, Clone, PartialEq)]
pub struct ColMeta {
    /// Table qualifier ("" when the column is computed).
    pub table: String,
    pub name: String,
    pub sql_type: SqlType,
    /// Whether the column may hold NULL. Computed expressions are
    /// always nullable; only plain table columns mirror their
    /// `ColumnDef.nullable` (the wire encoder rejects NULL cells for
    /// NOT_NULL-flagged columns, so this must never overclaim).
    pub nullable: bool,
    /// The column is the table's primary key.
    pub primary: bool,
}

impl ColMeta {
    /// A nullable, unkeyed result column (computed expressions and the
    /// SHOW / EXPLAIN / @@sysvar outputs).
    pub fn computed(table: &str, name: &str, sql_type: SqlType) -> ColMeta {
        ColMeta {
            table: table.to_string(),
            name: name.to_string(),
            sql_type,
            nullable: true,
            primary: false,
        }
    }
}

/// Statement outcome: a rowset (SELECT/SHOW/EXPLAIN), an affected-rows
/// count (INSERT/UPDATE/DELETE), or plain OK (DDL/SET).
#[derive(Debug, Clone, PartialEq)]
pub enum ExecOutcome {
    Rows {
        columns: Vec<ColMeta>,
        rows: Vec<Vec<crate::sql::storage::schema::Value>>,
    },
    Affected(u64),
    Ok,
}

/// Per-connection SQL session state (USE target + the open explicit
/// transaction). One instance lives in the frontend shim per connection.
#[derive(Debug, Default, Clone)]
pub struct SqlSession {
    pub db: String,
    /// Open BEGIN..COMMIT/ROLLBACK transaction, if any: a pinned
    /// snapshot plus the staged write set (see [`crate::sql::tx`]).
    pub txn: Option<crate::sql::tx::Txn>,
    /// Last `SET TRANSACTION ISOLATION LEVEL` (hyphenated MySQL form);
    /// `None` = the engine default, REPEATABLE-READ. The engine maps
    /// every accepted level onto its snapshot isolation.
    pub isolation: Option<String>,
    /// First AUTO_INCREMENT id generated by the most recent INSERT on
    /// this connection (MySQL `LAST_INSERT_ID()`; 0 = none).
    pub last_insert_id: i64,
    /// Immutable per-connection identity the session scalar functions
    /// (`USER()` / `CONNECTION_ID()`) read: set once by the frontend
    /// at handshake time, never mutated afterwards. Pure data -- the
    /// functions see it through per-exec substitution
    /// ([`session_funcs`]), never a global.
    pub info: SessionInfo,
}

/// Connection identity for the session scalar functions. A snapshot of
/// handshake facts (authenticated user, peer host, connection id); the
/// default is the "no frontend" shape of in-process callers (id 0,
/// `user@localhost`), so tests and embedded execution get honest,
/// stable values instead of fabrications.
#[derive(Debug, Clone, PartialEq)]
pub struct SessionInfo {
    /// `user@host` exactly as `USER()` / `CURRENT_USER()` render it.
    pub user: String,
    /// The connection id the handshake advertised (`CONNECTION_ID()`).
    pub connection_id: i64,
}

impl Default for SessionInfo {
    fn default() -> SessionInfo {
        SessionInfo {
            user: "root@localhost".to_string(),
            connection_id: 0,
        }
    }
}

/// The engine's implicit database when the session ran no `USE` (the
/// single-database model: every unqualified table name lives here).
pub const DEFAULT_DB: &str = "rdb";

/// Execute one statement against the shared engine state.
pub async fn execute(
    shared: &Shared,
    sess: &mut SqlSession,
    mut stmt: Statement,
) -> SqlResult<ExecOutcome> {
    let start = std::time::Instant::now();
    let kind = stmt.metric_kind();
    // Session scalar functions bind PER EXECUTION (a prepared statement
    // re-run after a `USE` must see the new database): the substitution
    // runs on every execute, before dispatch.
    session_funcs::substitute(
        &mut stmt,
        &session_funcs::SessionState {
            db: if sess.db.is_empty() {
                DEFAULT_DB.to_string()
            } else {
                sess.db.clone()
            },
            info: sess.info.clone(),
        },
    );
    let out = dispatch(shared, sess, stmt).await;
    crate::monitor::observe_sql_latency(
        &shared.monitor,
        kind,
        start.elapsed().as_secs_f64() * 1000.0,
    );
    out
}

async fn dispatch(
    shared: &Shared,
    sess: &mut SqlSession,
    stmt: Statement,
) -> SqlResult<ExecOutcome> {
    // DDL mutates the raft-replicated catalog; refusing it inside an
    // open transaction keeps snapshot reads consistent with the schema
    // they were planned against.
    if sess.txn.is_some()
        && matches!(
            stmt,
            Statement::CreateTable { .. }
                | Statement::DropTable { .. }
                | Statement::CreateIndex { .. }
                | Statement::DropIndex { .. }
                // TRUNCATE/RENAME are DDL exactly like CREATE/DROP
                // (decision point 5): reject in-txn, never stage.
                | Statement::TruncateTable { .. }
                | Statement::RenameTable { .. }
        )
    {
        return Err(SqlError::new(
            ErrorCode::TxnDdl,
            "DDL not allowed inside a transaction".to_string(),
        ));
    }
    match stmt {
        Statement::Begin => {
            // MySQL semantics: BEGIN implicitly commits any open txn.
            if let Some(txn) = sess.txn.take() {
                tx::commit(shared, txn).await?;
            }
            // Pin the snapshot to the cluster's latest applied ts (a
            // follower's own block lease can lag the raft cursor).
            shared.sql_ts.sync_cursor_frontier();
            sess.txn = Some(tx::begin(&shared.sql_ts));
            Ok(ExecOutcome::Ok)
        }
        Statement::Commit => match sess.txn.take() {
            Some(txn) => {
                tx::commit(shared, txn).await?;
                Ok(ExecOutcome::Ok)
            }
            None => Ok(ExecOutcome::Ok),
        },
        Statement::Rollback => {
            if let Some(txn) = sess.txn.take() {
                tx::rollback(&shared.sql_ts, txn);
            }
            Ok(ExecOutcome::Ok)
        }
        Statement::CreateTable { .. }
        | Statement::DropTable { .. }
        | Statement::CreateIndex { .. }
        | Statement::DropIndex { .. }
        | Statement::TruncateTable { .. }
        | Statement::RenameTable { .. } => ddl::run(shared, stmt).await,
        Statement::Insert { .. } => write::insert(shared, sess, stmt).await,
        Statement::Update { .. } => write::update(shared, sess, stmt).await,
        Statement::Delete { .. } => write::delete(shared, sess, stmt).await,
        Statement::Select(q) => {
            let (columns, rows) = select::run(shared, sess, q).await?;
            Ok(ExecOutcome::Rows { columns, rows })
        }
        Statement::SelectCompound(cq) => {
            let (columns, rows) = set_ops::run_statement(shared, sess, &cq).await?;
            Ok(ExecOutcome::Rows { columns, rows })
        }
        Statement::Explain(inner) => select::explain(shared, &inner),
        Statement::ShowTables
        | Statement::ShowColumns(_)
        | Statement::ShowIndexes(_)
        | Statement::ShowCreateTable(_)
        | Statement::ShowDatabases
        | Statement::ShowVariables { .. }
        | Statement::ShowStatus { .. } => show::run(shared, sess, &stmt),
        Statement::Use(db) => {
            sess.db = db;
            Ok(ExecOutcome::Ok)
        }
        Statement::SetIgnored => Ok(ExecOutcome::Ok),
        Statement::SetIsolation { level } => {
            // Stored for `@@transaction_isolation` reporting; the
            // engine runs one isolation (snapshot = REPEATABLE READ).
            sess.isolation = Some(level.replace(' ', "-"));
            Ok(ExecOutcome::Ok)
        }
        // SAVEPOINT family: real semantics over the staged write set.
        // MySQL starts an implicit transaction for a bare SAVEPOINT.
        Statement::Savepoint(name) => {
            if sess.txn.is_none() {
                shared.sql_ts.sync_cursor_frontier();
                sess.txn = Some(tx::begin(&shared.sql_ts));
            }
            tx::savepoint(sess.txn.as_mut().expect("txn begun above"), &name);
            Ok(ExecOutcome::Ok)
        }
        Statement::RollbackTo { name } => match sess.txn.as_mut() {
            Some(txn) => {
                tx::rollback_to(txn, &name)?;
                Ok(ExecOutcome::Ok)
            }
            None => Err(tx::unknown_savepoint(&name)),
        },
        Statement::ReleaseSavepoint { name } => match sess.txn.as_mut() {
            Some(txn) => {
                tx::release_savepoint(txn, &name)?;
                Ok(ExecOutcome::Ok)
            }
            None => Err(tx::unknown_savepoint(&name)),
        },
    }
}
