bind: 127.0.0.1:32680
store_path: /tmp/
raft_http_bind_address: 127.0.0.1:12680
raft_token: "6Mwqjg7TF9jcnF8PRxrq7jK3pG3DZ28fy5guk3Hm264smyftmuhUGtz5mssHfG7Ztg23j4FMb5qmpxdhBusfpevkveyR93eNfx6uv5YEZYyczfdYn4rpKxcRxiXhirik"
raft_bind_address: 127.0.0.1:22680
monitor_addr: 127.0.0.1:42680
# cluster_slots_stable_instances: xxx,xxx,xxx,xx
# cluster_migrate_instances: xxx,xxx,xxx:src1_slot:cur_slot:src2_slot
# cluster_slots_version: 1