bind: 127.0.0.1:32683
store_path: /tmp/
backup_target: 127.0.0.1:32685
backup_bind: 127.0.0.1:32685
backup_store_path: /tmp/backup
backup_monitor_addr: 127.0.0.1:42685
raft_http_bind_address: 127.0.0.1:12683
raft_token: "6Mwqjg7TF9jcnF8PRxrq7jK3pG3DZ28fy5guk3Hm264smyftmuhUGtz5mssHfG7Ztg23j4FMb5qmpxdhBusfpevkveyR93eNfx6uv5YEZYyczfdYn4rpKxcRxiXhirik"
raft_bind_address: 127.0.0.1:22683
monitor_addr: 127.0.0.1:42683
# cluster_slots_stable_instances: xxx,xxx,xxx,xx
# cluster_migrate_instances: xxx,xxx,xxx:src1_slot:cur_slot:src2_slot
# cluster_slots_version: 1