bind: 127.0.0.1:32685
store_path: /tmp/
backup_bind: 127.0.0.1:32686
backup_store_path: /tmp/backup
raft_http_bind_address: 127.0.0.1:12685
raft_token: "6Mwqjg7TF9jcnF8PRxrq7jK3pG3DZ28fy5guk3Hm264smyftmuhUGtz5mssHfG7Ztg23j4FMb5qmpxdhBusfpevkveyR93eNfx6uv5YEZYyczfdYn4rpKxcRxiXhirik"
raft_bind_address: 127.0.0.1:22685
monitor_addr: 127.0.0.1:42685